line-length = 120
target-version = 'py37'

[lint]
select = [
    "ALL",
]
preview = false

ignore = [
    # NXP STUFF
    'PT009',
    'PTH', # Ignore all pathlib
    # Pathlib things
    'ANN001',
    'ANN204',
    'ANN205',
    'ANN202',
    'ANN201',
    'DTZ005',

    # End NXP STUFF

    'PLR6104', # https://github.com/astral-sh/ruff/issues/12890
    'PLR0904',

    'CPY001',
    'UP032', # F strings instead of .format

    'LOG015', # Root logger
    'G001', # Format in log
    'G004', # F-string in log


    "S101", # assert
    "T201", # print


    # Ignored for ruff formatter https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",


    # Docstring rules ignored for now
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D415",

    "FIX002", # to-do messages
    "TD001",
    "TD002",
    "TD003",
    "TD004",
    "TD005"
]

[lint.pydocstyle]
convention = 'numpy'

[format]
quote-style = 'single'
